### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by KyleKing** [atugushev/flake8-printf-formatting#3]
In Python 3.8, the importlib_metadata package was implemented in the standard library as `importlib.metadata` ([Python docs](https://docs.python.org/3.8/library/importlib.metadata.html))

You may want to add this snippet to `flake8_printf_formatting.py` and update the install requires in `setup.cfg`

```py
try:
    import importlib.metadata as importlib_metadata
except ImportError:
    import importlib_metadata  # python_version<'3.8'
```

I can also submit a PR if that would be of interest

---

For searchability, this is the error from flake8: `flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "MOD" due to No module named 'importlib_metadata'.`

**Comment by atugushev** [comment]
Hello @KyleKing,

Thanks for the report! PRs are highly welcomed and appreciated ☺️
